# Config version: 2024-12-09
graphqlapi:
  port: 4000
  validatorType: "jwk"
  jwtJwksUrl: ""
  enableIntrospection: true

db:
  url: "postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable"
  maxConns: 10
  minConns: 2
  maxConnLifetime: "30m"
  maxConnIdleTime: "5m"

openrouter:
  apiKey: ""

openai:
  apiKey: ""
